name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment for your job

    steps:
      # Check out the code from your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16" # Use your preferred Node.js version

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Run Playwright tests
      - name: Run Playwright tests
        run: |
          npx playwright install  # Install necessary browsers for Playwright
          npm test  # or use your custom script to run tests
